= Capitalize Titles

Java API and command line program to capitalize English titles according to the APA style (in a best-effort manner).

_Caution:_ It doesn't perform any Grammar analysis and thus might incorrectly return some prepositions, conjunctions, adjective, or adverbs, such as yet, out, so, etc.

_Caution No 2:_ Has been created by a non-native speaker 🙂


== Features

- Capitalizes English titles according to APA + 
  Example: `a river runs through the city` -> `A River Runs Through the City` + 
  Example: `my cloud-native deployment` -> `My Cloud-Native Deployment`
- Ignores trailing special characters (helpful for AsciiDoc & Markdown content) + 
  Example: `=== a river runs through the city` -> `=== A River Runs Through the City`
- Honors certain characters as stop characters + 
  Example: `breaking news: a river runs through the city` -> `Breaking News: A River Runs Through the City`


== Building

To build a native executable, execute: `mvn package -P native`

This will create an executable binary under `target/capitalize-title-runner`


== Command Line Usage

----
USAGE:
    capitalize-title <title>
                           Capitalizes the provided title according to AP style
    capitalize-title -
                           Reads the title from stdin.
EXAMPLES:
    capitalize-title a river runs through the city
                           Returns: A River Runs Through the City
    cat titles.txt | capitalize-title -
                           Capitalizes each line in the titles.txt file
----
